// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/api/v1/augusta.proto

package augusta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_OK    Status = 0
	Status_ERROR Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	Status_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_api_v1_augusta_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_internal_api_v1_augusta_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_api_v1_augusta_proto_rawDescGZIP(), []int{0}
}

type Task struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TaskType       string                 `protobuf:"bytes,3,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Command        []byte                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Disabled       bool                   `protobuf:"varint,5,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Retries        int32                  `protobuf:"varint,6,opt,name=retries,proto3" json:"retries,omitempty"`
	CurrentRetries int32                  `protobuf:"varint,7,opt,name=current_retries,json=currentRetries,proto3" json:"current_retries,omitempty"`
	Epsilon        string                 `protobuf:"bytes,8,opt,name=epsilon,proto3" json:"epsilon,omitempty"`
	LastSuccess    int64                  `protobuf:"varint,9,opt,name=last_success,json=lastSuccess,proto3" json:"last_success,omitempty"`
	LastError      int64                  `protobuf:"varint,10,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	Schedule       string                 `protobuf:"bytes,11,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Status         string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	NextRunAt      int64                  `protobuf:"varint,13,opt,name=next_run_at,json=nextRunAt,proto3" json:"next_run_at,omitempty"`
	LastRunAt      int64                  `protobuf:"varint,14,opt,name=last_run_at,json=lastRunAt,proto3" json:"last_run_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_internal_api_v1_augusta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_v1_augusta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_internal_api_v1_augusta_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *Task) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Task) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *Task) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *Task) GetCurrentRetries() int32 {
	if x != nil {
		return x.CurrentRetries
	}
	return 0
}

func (x *Task) GetEpsilon() string {
	if x != nil {
		return x.Epsilon
	}
	return ""
}

func (x *Task) GetLastSuccess() int64 {
	if x != nil {
		return x.LastSuccess
	}
	return 0
}

func (x *Task) GetLastError() int64 {
	if x != nil {
		return x.LastError
	}
	return 0
}

func (x *Task) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetNextRunAt() int64 {
	if x != nil {
		return x.NextRunAt
	}
	return 0
}

func (x *Task) GetLastRunAt() int64 {
	if x != nil {
		return x.LastRunAt
	}
	return 0
}

type RegisterWorker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	SupportedTags []string               `protobuf:"bytes,2,rep,name=supported_tags,json=supportedTags,proto3" json:"supported_tags,omitempty"` //Todo: add more info about the worker
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorker) Reset() {
	*x = RegisterWorker{}
	mi := &file_internal_api_v1_augusta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorker) ProtoMessage() {}

func (x *RegisterWorker) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_v1_augusta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorker.ProtoReflect.Descriptor instead.
func (*RegisterWorker) Descriptor() ([]byte, []int) {
	return file_internal_api_v1_augusta_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterWorker) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterWorker) GetSupportedTags() []string {
	if x != nil {
		return x.SupportedTags
	}
	return nil
}

type TaskBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskBatch) Reset() {
	*x = TaskBatch{}
	mi := &file_internal_api_v1_augusta_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskBatch) ProtoMessage() {}

func (x *TaskBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_v1_augusta_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskBatch.ProtoReflect.Descriptor instead.
func (*TaskBatch) Descriptor() ([]byte, []int) {
	return file_internal_api_v1_augusta_proto_rawDescGZIP(), []int{2}
}

func (x *TaskBatch) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type TaskHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ActiveTaskIds []string               `protobuf:"bytes,2,rep,name=active_task_ids,json=activeTaskIds,proto3" json:"active_task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskHeartbeat) Reset() {
	*x = TaskHeartbeat{}
	mi := &file_internal_api_v1_augusta_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskHeartbeat) ProtoMessage() {}

func (x *TaskHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_v1_augusta_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskHeartbeat.ProtoReflect.Descriptor instead.
func (*TaskHeartbeat) Descriptor() ([]byte, []int) {
	return file_internal_api_v1_augusta_proto_rawDescGZIP(), []int{3}
}

func (x *TaskHeartbeat) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskHeartbeat) GetActiveTaskIds() []string {
	if x != nil {
		return x.ActiveTaskIds
	}
	return nil
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=augusta.v1.Status" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_internal_api_v1_augusta_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_v1_augusta_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_internal_api_v1_augusta_proto_rawDescGZIP(), []int{4}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *TaskResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_Register
	//	*ClientMessage_Heartbeat
	//	*ClientMessage_Result
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_internal_api_v1_augusta_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_v1_augusta_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_internal_api_v1_augusta_proto_rawDescGZIP(), []int{5}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetRegister() *RegisterWorker {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *ClientMessage) GetHeartbeat() *TaskHeartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ClientMessage) GetResult() *TaskResult {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Register struct {
	Register *RegisterWorker `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type ClientMessage_Heartbeat struct {
	Heartbeat *TaskHeartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type ClientMessage_Result struct {
	Result *TaskResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

func (*ClientMessage_Register) isClientMessage_Payload() {}

func (*ClientMessage_Heartbeat) isClientMessage_Payload() {}

func (*ClientMessage_Result) isClientMessage_Payload() {}

type RegisterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_internal_api_v1_augusta_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_v1_augusta_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_internal_api_v1_augusta_proto_rawDescGZIP(), []int{6}
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Ack
	//	*ServerMessage_Tasks
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_internal_api_v1_augusta_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_v1_augusta_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_internal_api_v1_augusta_proto_rawDescGZIP(), []int{7}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetAck() *RegisterAck {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ServerMessage) GetTasks() *TaskBatch {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Tasks); ok {
			return x.Tasks
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Ack struct {
	Ack *RegisterAck `protobuf:"bytes,1,opt,name=ack,proto3,oneof"`
}

type ServerMessage_Tasks struct {
	Tasks *TaskBatch `protobuf:"bytes,2,opt,name=tasks,proto3,oneof"`
}

func (*ServerMessage_Ack) isServerMessage_Payload() {}

func (*ServerMessage_Tasks) isServerMessage_Payload() {}

var File_internal_api_v1_augusta_proto protoreflect.FileDescriptor

const file_internal_api_v1_augusta_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/api/v1/augusta.proto\x12\n" +
	"augusta.v1\"\x90\x03\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\ttask_type\x18\x03 \x01(\tR\btaskType\x12\x18\n" +
	"\acommand\x18\x04 \x01(\fR\acommand\x12\x1a\n" +
	"\bdisabled\x18\x05 \x01(\bR\bdisabled\x12\x18\n" +
	"\aretries\x18\x06 \x01(\x05R\aretries\x12'\n" +
	"\x0fcurrent_retries\x18\a \x01(\x05R\x0ecurrentRetries\x12\x18\n" +
	"\aepsilon\x18\b \x01(\tR\aepsilon\x12!\n" +
	"\flast_success\x18\t \x01(\x03R\vlastSuccess\x12\x1d\n" +
	"\n" +
	"last_error\x18\n" +
	" \x01(\x03R\tlastError\x12\x1a\n" +
	"\bschedule\x18\v \x01(\tR\bschedule\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x12\x1e\n" +
	"\vnext_run_at\x18\r \x01(\x03R\tnextRunAt\x12\x1e\n" +
	"\vlast_run_at\x18\x0e \x01(\x03R\tlastRunAt\"T\n" +
	"\x0eRegisterWorker\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12%\n" +
	"\x0esupported_tags\x18\x02 \x03(\tR\rsupportedTags\"3\n" +
	"\tTaskBatch\x12&\n" +
	"\x05tasks\x18\x01 \x03(\v2\x10.augusta.v1.TaskR\x05tasks\"T\n" +
	"\rTaskHeartbeat\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12&\n" +
	"\x0factive_task_ids\x18\x02 \x03(\tR\ractiveTaskIds\"v\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.augusta.v1.StatusR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xc1\x01\n" +
	"\rClientMessage\x128\n" +
	"\bregister\x18\x01 \x01(\v2\x1a.augusta.v1.RegisterWorkerH\x00R\bregister\x129\n" +
	"\theartbeat\x18\x02 \x01(\v2\x19.augusta.v1.TaskHeartbeatH\x00R\theartbeat\x120\n" +
	"\x06result\x18\x03 \x01(\v2\x16.augusta.v1.TaskResultH\x00R\x06resultB\t\n" +
	"\apayload\"\r\n" +
	"\vRegisterAck\"v\n" +
	"\rServerMessage\x12+\n" +
	"\x03ack\x18\x01 \x01(\v2\x17.augusta.v1.RegisterAckH\x00R\x03ack\x12-\n" +
	"\x05tasks\x18\x02 \x01(\v2\x15.augusta.v1.TaskBatchH\x00R\x05tasksB\t\n" +
	"\apayload*\x1b\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x012`\n" +
	"\x10SchedulerService\x12L\n" +
	"\x0eConnectSession\x12\x19.augusta.v1.ClientMessage\x1a\x19.augusta.v1.ServerMessage\"\x00(\x010\x01B)Z'https://github.com/knightfall22/augustab\x06proto3"

var (
	file_internal_api_v1_augusta_proto_rawDescOnce sync.Once
	file_internal_api_v1_augusta_proto_rawDescData []byte
)

func file_internal_api_v1_augusta_proto_rawDescGZIP() []byte {
	file_internal_api_v1_augusta_proto_rawDescOnce.Do(func() {
		file_internal_api_v1_augusta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_v1_augusta_proto_rawDesc), len(file_internal_api_v1_augusta_proto_rawDesc)))
	})
	return file_internal_api_v1_augusta_proto_rawDescData
}

var file_internal_api_v1_augusta_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_api_v1_augusta_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_api_v1_augusta_proto_goTypes = []any{
	(Status)(0),            // 0: augusta.v1.Status
	(*Task)(nil),           // 1: augusta.v1.Task
	(*RegisterWorker)(nil), // 2: augusta.v1.RegisterWorker
	(*TaskBatch)(nil),      // 3: augusta.v1.TaskBatch
	(*TaskHeartbeat)(nil),  // 4: augusta.v1.TaskHeartbeat
	(*TaskResult)(nil),     // 5: augusta.v1.TaskResult
	(*ClientMessage)(nil),  // 6: augusta.v1.ClientMessage
	(*RegisterAck)(nil),    // 7: augusta.v1.RegisterAck
	(*ServerMessage)(nil),  // 8: augusta.v1.ServerMessage
}
var file_internal_api_v1_augusta_proto_depIdxs = []int32{
	1, // 0: augusta.v1.TaskBatch.tasks:type_name -> augusta.v1.Task
	0, // 1: augusta.v1.TaskResult.status:type_name -> augusta.v1.Status
	2, // 2: augusta.v1.ClientMessage.register:type_name -> augusta.v1.RegisterWorker
	4, // 3: augusta.v1.ClientMessage.heartbeat:type_name -> augusta.v1.TaskHeartbeat
	5, // 4: augusta.v1.ClientMessage.result:type_name -> augusta.v1.TaskResult
	7, // 5: augusta.v1.ServerMessage.ack:type_name -> augusta.v1.RegisterAck
	3, // 6: augusta.v1.ServerMessage.tasks:type_name -> augusta.v1.TaskBatch
	6, // 7: augusta.v1.SchedulerService.ConnectSession:input_type -> augusta.v1.ClientMessage
	8, // 8: augusta.v1.SchedulerService.ConnectSession:output_type -> augusta.v1.ServerMessage
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_internal_api_v1_augusta_proto_init() }
func file_internal_api_v1_augusta_proto_init() {
	if File_internal_api_v1_augusta_proto != nil {
		return
	}
	file_internal_api_v1_augusta_proto_msgTypes[5].OneofWrappers = []any{
		(*ClientMessage_Register)(nil),
		(*ClientMessage_Heartbeat)(nil),
		(*ClientMessage_Result)(nil),
	}
	file_internal_api_v1_augusta_proto_msgTypes[7].OneofWrappers = []any{
		(*ServerMessage_Ack)(nil),
		(*ServerMessage_Tasks)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_v1_augusta_proto_rawDesc), len(file_internal_api_v1_augusta_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_v1_augusta_proto_goTypes,
		DependencyIndexes: file_internal_api_v1_augusta_proto_depIdxs,
		EnumInfos:         file_internal_api_v1_augusta_proto_enumTypes,
		MessageInfos:      file_internal_api_v1_augusta_proto_msgTypes,
	}.Build()
	File_internal_api_v1_augusta_proto = out.File
	file_internal_api_v1_augusta_proto_goTypes = nil
	file_internal_api_v1_augusta_proto_depIdxs = nil
}
